### PR TITLE
Add suggested extensions to dependency array

### LINKED ISSUE #7: Suggests array is not uploaded
Looking at https://github.com/NamelessCoder/typo3-repository-client/blob/master/src/ExtensionUploadPacker.php#L107-L108 it seems that the suggests array is not prepared for upload. Any reasons for that?

### PR DESCRIPTION
**Pull request by helhum**
It is important to not loose this dependency information
while uploading to TER.

Fixes #7

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Looks like it does the trick - and thanks for not only doing the tests but also catching the unused variables there :)

Just a single thing to do: `git commit --amend -m "[TASK] Add suggested extensions to dependencies array" && git push -f`.

Thanks!

**Comment by helhum** [comment]
> Just a single thing to do

[x] done

**Comment by helhum** [comment]
Thanks!

**Comment by NamelessCoder** [comment]
Thank you too! :)

**Pull request merged**
