### PR TITLE
Fix help text of upload cli command

### PR DESCRIPTION
**Pull request by liayn**
The parameter list is now shown in the correct order.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Thanks Markus - before we go, would you mind doing a `git commit --amend -m "[DOC] Fix help text of upload cli command" && git push -f`? Thanks :)

**Comment by liayn** [comment]
sure, will update

**Comment by helhum** [comment]
this one is merged already, thus can be closed

**Comment by NamelessCoder** [comment]
Indeed it is - thanks guys!

**Pull request closed without merging**
