### PR TITLE
[TASK] Require soap php extension

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by simonschaufi** [comment]
@NamelessCoder do you still have php7.0 running to execute `composer update` as I have only php7.2 installed?

**Comment by NamelessCoder** [comment]
@simonschaufi Should work just fine if you avoid changing the dependencies aside from adding ext-soap, but you may need to run composer update with `--ignore-platform-reqs` to ignore your local php version's implied constraints.

In general you should be careful not to change more than one thing at a time (per PR).

**Comment by simonschaufi** [comment]
The thing is that some dependencies don't support php 7.0 any more which I updated. That's why I need php 7.0 to simulate that.

`phpdocumentor/reflection-common 2.2.0 requires php ^7.2 || ^8.0 -> your PHP version (7.1.27) does not satisfy that requirement.`

The alternative would be to bump the php requirements but then you should release a new major version as this would be breaking

**Comment by NamelessCoder** [comment]
> The thing is that some dependencies don't support php 7.0 any more which I updated. 

I'm not sure I follow - *updating* a dep is unlikely to *decrease* the minimum supported PHP version, afaik. If you simply don't touch the other dependencies you should still be able to do a composer update as long as you specify to ignore platform reqs (which would include the PHP version). You might not be able to run the CLI tests but that's another issue ;)

**Comment by simonschaufi** [comment]
I simulate the php version now in order to fake the php version for composer update and now the tests should be fine again.

**Comment by NamelessCoder** [comment]
Try something for me please. Revert all changes except for the single line that adds `"ext-soap": "*"` to dependencies, then do `composer update --ignore-platform-reqs`. The other changes shouldn't be necessary at all in this PR.

**Comment by simonschaufi** [comment]
This leads again to an update of `phpdocumentor/reflection-common` which doesn't support php 7.0

```
Installing phpdocumentor/reflection-common (2.2.0): Loading from cache
```

**Comment by NamelessCoder** [comment]
Also if you delete the `vendor` folder? I suspect this is caused by composer attempting to update something that's not truly a dependency but exists in your `vendor` folder from previous version bumps of dependencies.

EDIT: nevermind, I see what you mean. It doesn't error, it just installs the package which then isn't compatible. I initially understood it as composer errors out.

**Comment by simonschaufi** [comment]
yes, starting from zero

**Comment by NamelessCoder** [comment]
Let me think about this a bit, it may make more sense to release a new major version which also adds strict types and required PHP ^7.2.

**Comment by simonschaufi** [comment]
@NamelessCoder ping

**Comment by simonschaufi** [comment]
@NamelessCoder Can you merge this, bump PHP version to 7.2 and make a new major release? The last release was a long time ago already

**Pull request merged**
